[theme]
primaryColor = "#16a34a"
backgroundColor = "#f0fdf4"
secondaryBackgroundColor = "#ffffff"
textColor = "#1f2937"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
